// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CppMMO.Protocol
{

public enum PacketId : ushort
{
  NONE = 0,
  C_Login = 1,
  S_LoginSuccess = 2,
  S_LoginFailure = 3,
  C_Chat = 4,
  S_Chat = 5,
  C_MoveInput = 6,
  S_PlayerMoveState = 7,
  C_ChangeZone = 8,
  S_EnterZone = 9,
  S_LeaveZone = 10,
  S_PlayerEnterZone = 11,
  S_PlayerLeaveZone = 12,
  S_PlayerHpUpdate = 13,
};


}
