// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CppMMO.Protocol
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct S_PlayerHpUpdate : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static S_PlayerHpUpdate GetRootAsS_PlayerHpUpdate(ByteBuffer _bb) { return GetRootAsS_PlayerHpUpdate(_bb, new S_PlayerHpUpdate()); }
  public static S_PlayerHpUpdate GetRootAsS_PlayerHpUpdate(ByteBuffer _bb, S_PlayerHpUpdate obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public S_PlayerHpUpdate __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long PlayerId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int CurrentHp { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<CppMMO.Protocol.S_PlayerHpUpdate> CreateS_PlayerHpUpdate(FlatBufferBuilder builder,
      long player_id = 0,
      int current_hp = 0) {
    builder.StartTable(2);
    S_PlayerHpUpdate.AddPlayerId(builder, player_id);
    S_PlayerHpUpdate.AddCurrentHp(builder, current_hp);
    return S_PlayerHpUpdate.EndS_PlayerHpUpdate(builder);
  }

  public static void StartS_PlayerHpUpdate(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPlayerId(FlatBufferBuilder builder, long playerId) { builder.AddLong(0, playerId, 0); }
  public static void AddCurrentHp(FlatBufferBuilder builder, int currentHp) { builder.AddInt(1, currentHp, 0); }
  public static Offset<CppMMO.Protocol.S_PlayerHpUpdate> EndS_PlayerHpUpdate(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CppMMO.Protocol.S_PlayerHpUpdate>(o);
  }
}


static public class S_PlayerHpUpdateVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PlayerId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*CurrentHp*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
