# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

class Packet(object):
    NONE = 0
    C_Login = 1
    S_LoginSuccess = 2
    S_LoginFailure = 3
    C_Chat = 4
    S_Chat = 5
    C_Move = 6
    S_PlayerMove = 7
    S_PlayerHpUpdate = 8
    C_ChangeZone = 9
    S_EnterZone = 10
    S_LeaveZone = 11
    S_PlayerEnterZone = 12
    S_PlayerLeaveZone = 13
