# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class S_LoginSuccess(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = S_LoginSuccess()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsS_LoginSuccess(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # S_LoginSuccess
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # S_LoginSuccess
    def PlayerInfo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from CppMMO.Protocol.PlayerInfo import PlayerInfo
            obj = PlayerInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # S_LoginSuccess
    def CommandId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def S_LoginSuccessStart(builder):
    builder.StartObject(2)

def Start(builder):
    S_LoginSuccessStart(builder)

def S_LoginSuccessAddPlayerInfo(builder, playerInfo):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(playerInfo), 0)

def AddPlayerInfo(builder, playerInfo):
    S_LoginSuccessAddPlayerInfo(builder, playerInfo)

def S_LoginSuccessAddCommandId(builder, commandId):
    builder.PrependInt64Slot(1, commandId, 0)

def AddCommandId(builder, commandId):
    S_LoginSuccessAddCommandId(builder, commandId)

def S_LoginSuccessEnd(builder):
    return builder.EndObject()

def End(builder):
    return S_LoginSuccessEnd(builder)
