# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class S_PlayerHpUpdate(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = S_PlayerHpUpdate()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsS_PlayerHpUpdate(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # S_PlayerHpUpdate
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # S_PlayerHpUpdate
    def PlayerId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # S_PlayerHpUpdate
    def CurrentHp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def S_PlayerHpUpdateStart(builder):
    builder.StartObject(2)

def Start(builder):
    S_PlayerHpUpdateStart(builder)

def S_PlayerHpUpdateAddPlayerId(builder, playerId):
    builder.PrependInt64Slot(0, playerId, 0)

def AddPlayerId(builder, playerId):
    S_PlayerHpUpdateAddPlayerId(builder, playerId)

def S_PlayerHpUpdateAddCurrentHp(builder, currentHp):
    builder.PrependInt32Slot(1, currentHp, 0)

def AddCurrentHp(builder, currentHp):
    S_PlayerHpUpdateAddCurrentHp(builder, currentHp)

def S_PlayerHpUpdateEnd(builder):
    return builder.EndObject()

def End(builder):
    return S_PlayerHpUpdateEnd(builder)
