# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class C_ChangeZone(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = C_ChangeZone()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsC_ChangeZone(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # C_ChangeZone
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # C_ChangeZone
    def TargetZoneId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # C_ChangeZone
    def CommandId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def C_ChangeZoneStart(builder):
    builder.StartObject(2)

def Start(builder):
    C_ChangeZoneStart(builder)

def C_ChangeZoneAddTargetZoneId(builder, targetZoneId):
    builder.PrependInt32Slot(0, targetZoneId, 0)

def AddTargetZoneId(builder, targetZoneId):
    C_ChangeZoneAddTargetZoneId(builder, targetZoneId)

def C_ChangeZoneAddCommandId(builder, commandId):
    builder.PrependInt64Slot(1, commandId, 0)

def AddCommandId(builder, commandId):
    C_ChangeZoneAddCommandId(builder, commandId)

def C_ChangeZoneEnd(builder):
    return builder.EndObject()

def End(builder):
    return C_ChangeZoneEnd(builder)
