# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class C_Move(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = C_Move()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsC_Move(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # C_Move
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # C_Move
    def TargetPosition(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from CppMMO.Protocol.Vec2 import Vec2
            obj = Vec2()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # C_Move
    def CommandId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def C_MoveStart(builder):
    builder.StartObject(2)

def Start(builder):
    C_MoveStart(builder)

def C_MoveAddTargetPosition(builder, targetPosition):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(targetPosition), 0)

def AddTargetPosition(builder, targetPosition):
    C_MoveAddTargetPosition(builder, targetPosition)

def C_MoveAddCommandId(builder, commandId):
    builder.PrependInt64Slot(1, commandId, 0)

def AddCommandId(builder, commandId):
    C_MoveAddCommandId(builder, commandId)

def C_MoveEnd(builder):
    return builder.EndObject()

def End(builder):
    return C_MoveEnd(builder)
