# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

class Packet(object):
    NONE = 0
    C_Login = 1
    S_LoginSuccess = 2
    S_LoginFailure = 3
    C_Chat = 4
    S_Chat = 5
    C_PlayerInput = 6
    S_WorldSnapshot = 7
    S_StateCorrection = 8
    S_GameTick = 9
    C_EnterZone = 10
    S_ZoneEntered = 11
    S_PlayerJoined = 12
    S_PlayerLeft = 13
