// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CppMMO.Protocol
{

public enum Packet : byte
{
  NONE = 0,
  C_Login = 1,
  S_LoginSuccess = 2,
  S_LoginFailure = 3,
  C_Chat = 4,
  S_Chat = 5,
  C_Move = 6,
  S_PlayerMove = 7,
  S_PlayerHpUpdate = 8,
  C_ChangeZone = 9,
  S_EnterZone = 10,
  S_LeaveZone = 11,
  S_PlayerEnterZone = 12,
  S_PlayerLeaveZone = 13,
};



static public class PacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((Packet)typeId)
    {
      case Packet.C_Login:
        result = CppMMO.Protocol.C_LoginVerify.Verify(verifier, tablePos);
        break;
      case Packet.S_LoginSuccess:
        result = CppMMO.Protocol.S_LoginSuccessVerify.Verify(verifier, tablePos);
        break;
      case Packet.S_LoginFailure:
        result = CppMMO.Protocol.S_LoginFailureVerify.Verify(verifier, tablePos);
        break;
      case Packet.C_Chat:
        result = CppMMO.Protocol.C_ChatVerify.Verify(verifier, tablePos);
        break;
      case Packet.S_Chat:
        result = CppMMO.Protocol.S_ChatVerify.Verify(verifier, tablePos);
        break;
      case Packet.C_Move:
        result = CppMMO.Protocol.C_MoveVerify.Verify(verifier, tablePos);
        break;
      case Packet.S_PlayerMove:
        result = CppMMO.Protocol.S_PlayerMoveVerify.Verify(verifier, tablePos);
        break;
      case Packet.S_PlayerHpUpdate:
        result = CppMMO.Protocol.S_PlayerHpUpdateVerify.Verify(verifier, tablePos);
        break;
      case Packet.C_ChangeZone:
        result = CppMMO.Protocol.C_ChangeZoneVerify.Verify(verifier, tablePos);
        break;
      case Packet.S_EnterZone:
        result = CppMMO.Protocol.S_EnterZoneVerify.Verify(verifier, tablePos);
        break;
      case Packet.S_LeaveZone:
        result = CppMMO.Protocol.S_LeaveZoneVerify.Verify(verifier, tablePos);
        break;
      case Packet.S_PlayerEnterZone:
        result = CppMMO.Protocol.S_PlayerEnterZoneVerify.Verify(verifier, tablePos);
        break;
      case Packet.S_PlayerLeaveZone:
        result = CppMMO.Protocol.S_PlayerLeaveZoneVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
