# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PlayerInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PlayerInfo()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPlayerInfo(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PlayerInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PlayerInfo
    def PlayerId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # PlayerInfo
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PlayerInfo
    def Position(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from CppMMO.Protocol.Vec2 import Vec2
            obj = Vec2()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PlayerInfo
    def Hp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # PlayerInfo
    def MaxHp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def PlayerInfoStart(builder):
    builder.StartObject(5)

def Start(builder):
    PlayerInfoStart(builder)

def PlayerInfoAddPlayerId(builder, playerId):
    builder.PrependInt64Slot(0, playerId, 0)

def AddPlayerId(builder, playerId):
    PlayerInfoAddPlayerId(builder, playerId)

def PlayerInfoAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    PlayerInfoAddName(builder, name)

def PlayerInfoAddPosition(builder, position):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(position), 0)

def AddPosition(builder, position):
    PlayerInfoAddPosition(builder, position)

def PlayerInfoAddHp(builder, hp):
    builder.PrependInt32Slot(3, hp, 0)

def AddHp(builder, hp):
    PlayerInfoAddHp(builder, hp)

def PlayerInfoAddMaxHp(builder, maxHp):
    builder.PrependInt32Slot(4, maxHp, 0)

def AddMaxHp(builder, maxHp):
    PlayerInfoAddMaxHp(builder, maxHp)

def PlayerInfoEnd(builder):
    return builder.EndObject()

def End(builder):
    return PlayerInfoEnd(builder)
