# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class S_LeaveZone(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = S_LeaveZone()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsS_LeaveZone(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # S_LeaveZone
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def S_LeaveZoneStart(builder):
    builder.StartObject(0)

def Start(builder):
    S_LeaveZoneStart(builder)

def S_LeaveZoneEnd(builder):
    return builder.EndObject()

def End(builder):
    return S_LeaveZoneEnd(builder)
