# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class S_PlayerJoined(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = S_PlayerJoined()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsS_PlayerJoined(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # S_PlayerJoined
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # S_PlayerJoined
    def PlayerInfo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from CppMMO.Protocol.PlayerInfo import PlayerInfo
            obj = PlayerInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def S_PlayerJoinedStart(builder):
    builder.StartObject(1)

def Start(builder):
    S_PlayerJoinedStart(builder)

def S_PlayerJoinedAddPlayerInfo(builder, playerInfo):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(playerInfo), 0)

def AddPlayerInfo(builder, playerInfo):
    S_PlayerJoinedAddPlayerInfo(builder, playerInfo)

def S_PlayerJoinedEnd(builder):
    return builder.EndObject()

def End(builder):
    return S_PlayerJoinedEnd(builder)
