# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class S_ZoneEntered(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = S_ZoneEntered()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsS_ZoneEntered(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # S_ZoneEntered
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # S_ZoneEntered
    def ZoneId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # S_ZoneEntered
    def MyPlayer(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .PlayerInfo import PlayerInfo
            obj = PlayerInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # S_ZoneEntered
    def OtherPlayers(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .PlayerInfo import PlayerInfo
            obj = PlayerInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # S_ZoneEntered
    def OtherPlayersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # S_ZoneEntered
    def OtherPlayersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def S_ZoneEnteredStart(builder):
    builder.StartObject(3)

def Start(builder):
    S_ZoneEnteredStart(builder)

def S_ZoneEnteredAddZoneId(builder, zoneId):
    builder.PrependInt32Slot(0, zoneId, 0)

def AddZoneId(builder, zoneId):
    S_ZoneEnteredAddZoneId(builder, zoneId)

def S_ZoneEnteredAddMyPlayer(builder, myPlayer):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(myPlayer), 0)

def AddMyPlayer(builder, myPlayer):
    S_ZoneEnteredAddMyPlayer(builder, myPlayer)

def S_ZoneEnteredAddOtherPlayers(builder, otherPlayers):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(otherPlayers), 0)

def AddOtherPlayers(builder, otherPlayers):
    S_ZoneEnteredAddOtherPlayers(builder, otherPlayers)

def S_ZoneEnteredStartOtherPlayersVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartOtherPlayersVector(builder, numElems):
    return S_ZoneEnteredStartOtherPlayersVector(builder, numElems)

def S_ZoneEnteredEnd(builder):
    return builder.EndObject()

def End(builder):
    return S_ZoneEnteredEnd(builder)
