# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Protocol

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UnifiedPacket(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UnifiedPacket()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUnifiedPacket(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UnifiedPacket
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UnifiedPacket
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # UnifiedPacket
    def DataType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # UnifiedPacket
    def Data(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def UnifiedPacketStart(builder):
    builder.StartObject(3)

def Start(builder):
    UnifiedPacketStart(builder)

def UnifiedPacketAddId(builder, id):
    builder.PrependUint16Slot(0, id, 0)

def AddId(builder, id):
    UnifiedPacketAddId(builder, id)

def UnifiedPacketAddDataType(builder, dataType):
    builder.PrependUint8Slot(1, dataType, 0)

def AddDataType(builder, dataType):
    UnifiedPacketAddDataType(builder, dataType)

def UnifiedPacketAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder, data):
    UnifiedPacketAddData(builder, data)

def UnifiedPacketEnd(builder):
    return builder.EndObject()

def End(builder):
    return UnifiedPacketEnd(builder)
